import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hinata Shoyo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Hinata listens to I WANT TO BE TALL by Jenna Marbles everyday in hopes that it will help him grow taller.
        </h1>

        <div className={styles.grid}>
          <img align="center" src="https://media.giphy.com/media/cRfnmVzTnPTNe/giphy.gif" width="700" height="500" />
        </div>
      </main>
    </div>
  )
}
